/**
 * Map of insight slug -> { en, es } slugs for locale switching.
 * Generated by scripts/generate-insights-locale-map.js - do not edit by hand.
 */
export const insightsLocaleMap: Record<string, { en: string; es: string }> = {
  "aot-autorizacion-ocupacion-territorio-venezuela-2026": {
    "en": "venezuela-territory-occupation-authorization-aot-2026",
    "es": "aot-autorizacion-ocupacion-territorio-venezuela-2026"
  },
  "venezuela-territory-occupation-authorization-aot-2026": {
    "en": "venezuela-territory-occupation-authorization-aot-2026",
    "es": "aot-autorizacion-ocupacion-territorio-venezuela-2026"
  },
  "appri-venezuela-colombia-entrada-vigor-2026": {
    "en": "venezuela-colombia-bit-entry-into-force-2026",
    "es": "appri-venezuela-colombia-entrada-vigor-2026"
  },
  "venezuela-colombia-bit-entry-into-force-2026": {
    "en": "venezuela-colombia-bit-entry-into-force-2026",
    "es": "appri-venezuela-colombia-entrada-vigor-2026"
  },
  "arbitraje-comercial-resolucion-controversias-venezuela": {
    "en": "commercial-arbitration-resolving-disputes-venezuela",
    "es": "arbitraje-comercial-resolucion-controversias-venezuela"
  },
  "commercial-arbitration-resolving-disputes-venezuela": {
    "en": "commercial-arbitration-resolving-disputes-venezuela",
    "es": "arbitraje-comercial-resolucion-controversias-venezuela"
  },
  "aspectos-constituir-empresa-venezuela": {
    "en": "incorporating-company-venezuela",
    "es": "aspectos-constituir-empresa-venezuela"
  },
  "incorporating-company-venezuela": {
    "en": "incorporating-company-venezuela",
    "es": "aspectos-constituir-empresa-venezuela"
  },
  "bonos-divisas-caracter-salarial-venezuela": {
    "en": "foreign-currency-bonuses-salary-venezuela",
    "es": "bonos-divisas-caracter-salarial-venezuela"
  },
  "foreign-currency-bonuses-salary-venezuela": {
    "en": "foreign-currency-bonuses-salary-venezuela",
    "es": "bonos-divisas-caracter-salarial-venezuela"
  },
  "cedca-new-arbitration-rules-2026-venezuela": {
    "en": "cedca-new-arbitration-rules-2026-venezuela",
    "es": "cedca-nuevo-reglamento-conciliacion-arbitraje-2026"
  },
  "cedca-nuevo-reglamento-conciliacion-arbitraje-2026": {
    "en": "cedca-new-arbitration-rules-2026-venezuela",
    "es": "cedca-nuevo-reglamento-conciliacion-arbitraje-2026"
  },
  "consultores-ambientales-venezuela-2026": {
    "en": "venezuela-environmental-consultants-2026",
    "es": "consultores-ambientales-venezuela-2026"
  },
  "venezuela-environmental-consultants-2026": {
    "en": "venezuela-environmental-consultants-2026",
    "es": "consultores-ambientales-venezuela-2026"
  },
  "corporate-good-standing-venezuela": {
    "en": "corporate-good-standing-venezuela",
    "es": "empresas-corporativamente-al-dia-es"
  },
  "empresas-corporativamente-al-dia-es": {
    "en": "corporate-good-standing-venezuela",
    "es": "empresas-corporativamente-al-dia-es"
  },
  "decreto-5364-ocupacion-bienes-venezuela-2026": {
    "en": "venezuela-decree-5364-property-occupation-2026",
    "es": "decreto-5364-ocupacion-bienes-venezuela-2026"
  },
  "venezuela-decree-5364-property-occupation-2026": {
    "en": "venezuela-decree-5364-property-occupation-2026",
    "es": "decreto-5364-ocupacion-bienes-venezuela-2026"
  },
  "electronic-signatures-venezuela-digital-risk-2026": {
    "en": "electronic-signatures-venezuela-digital-risk-2026",
    "es": "firmas-electronicas-venezuela-riesgo-digital-2026"
  },
  "firmas-electronicas-venezuela-riesgo-digital-2026": {
    "en": "electronic-signatures-venezuela-digital-risk-2026",
    "es": "firmas-electronicas-venezuela-riesgo-digital-2026"
  },
  "fintech-venezuela-itfb-regulation": {
    "en": "fintech-venezuela-itfb-regulation",
    "es": "fintech-venezuela-itfb-sudeban"
  },
  "fintech-venezuela-itfb-sudeban": {
    "en": "fintech-venezuela-itfb-regulation",
    "es": "fintech-venezuela-itfb-sudeban"
  },
  "fiscalizacion-seniat-venezuela-2026": {
    "en": "seniat-tax-audit-venezuela-2026",
    "es": "fiscalizacion-seniat-venezuela-2026"
  },
  "seniat-tax-audit-venezuela-2026": {
    "en": "seniat-tax-audit-venezuela-2026",
    "es": "fiscalizacion-seniat-venezuela-2026"
  },
  "locota-celerity-law-what-it-means": {
    "en": "locota-celerity-law-what-it-means",
    "es": "locota-celerity-law-what-it-means"
  },
  "nueva-licencia-ofac-asesoria-reestructuracion-deuda-venezolana": {
    "en": "ofac-general-license-58-venezuela-debt-restructuring-advisory-services",
    "es": "nueva-licencia-ofac-asesoria-reestructuracion-deuda-venezolana"
  },
  "ofac-general-license-58-venezuela-debt-restructuring-advisory-services": {
    "en": "ofac-general-license-58-venezuela-debt-restructuring-advisory-services",
    "es": "nueva-licencia-ofac-asesoria-reestructuracion-deuda-venezolana"
  },
  "ofac-amended-seven-venezuela-general-licenses-june-2026": {
    "en": "ofac-amended-seven-venezuela-general-licenses-june-2026",
    "es": "ofac-modifica-siete-licencias-generales-venezuela-junio-2026"
  },
  "ofac-modifica-siete-licencias-generales-venezuela-junio-2026": {
    "en": "ofac-amended-seven-venezuela-general-licenses-june-2026",
    "es": "ofac-modifica-siete-licencias-generales-venezuela-junio-2026"
  },
  "ofac-general-licenses-venezuela-april-2026": {
    "en": "ofac-general-licenses-venezuela-april-2026",
    "es": "ofac-licencias-generales-venezuela-abril-2026"
  },
  "ofac-licencias-generales-venezuela-abril-2026": {
    "en": "ofac-general-licenses-venezuela-april-2026",
    "es": "ofac-licencias-generales-venezuela-abril-2026"
  },
  "ofac-general-licenses-venezuela-march-2026": {
    "en": "ofac-general-licenses-venezuela-march-2026",
    "es": "ofac-licencias-generales-venezuela-marzo-2026"
  },
  "ofac-licencias-generales-venezuela-marzo-2026": {
    "en": "ofac-general-licenses-venezuela-march-2026",
    "es": "ofac-licencias-generales-venezuela-marzo-2026"
  },
  "payment-service-providers-venezuela": {
    "en": "payment-service-providers-venezuela",
    "es": "proveedores-servicios-pago-venezuela"
  },
  "proveedores-servicios-pago-venezuela": {
    "en": "payment-service-providers-venezuela",
    "es": "proveedores-servicios-pago-venezuela"
  },
  "reactivacion-hidrocarburos-electricidad-venezuela-eias-2026": {
    "en": "venezuela-oil-gas-electricity-reactivation-esia-2026",
    "es": "reactivacion-hidrocarburos-electricidad-venezuela-eias-2026"
  },
  "venezuela-oil-gas-electricity-reactivation-esia-2026": {
    "en": "venezuela-oil-gas-electricity-reactivation-esia-2026",
    "es": "reactivacion-hidrocarburos-electricidad-venezuela-eias-2026"
  },
  "should-venezuela-rejoin-icsid-bit-united-states-2026": {
    "en": "should-venezuela-rejoin-icsid-bit-united-states-2026",
    "es": "venezuela-regresar-ciadi-tpi-estados-unidos-2026"
  },
  "venezuela-regresar-ciadi-tpi-estados-unidos-2026": {
    "en": "should-venezuela-rejoin-icsid-bit-united-states-2026",
    "es": "venezuela-regresar-ciadi-tpi-estados-unidos-2026"
  },
  "venezuela-economic-revival-environmental-regulation": {
    "en": "venezuela-economic-revival-environmental-regulation",
    "es": "venezuela-reactivacion-economica-marco-regulatorio-ambiental"
  },
  "venezuela-reactivacion-economica-marco-regulatorio-ambiental": {
    "en": "venezuela-economic-revival-environmental-regulation",
    "es": "venezuela-reactivacion-economica-marco-regulatorio-ambiental"
  },
  "venezuela-securities-financing-four-mechanisms-2026": {
    "en": "venezuela-securities-financing-four-mechanisms-2026",
    "es": "venezuela-securities-financing-four-mechanisms-2026"
  },
  "venezuela-special-taxpayers-seniat": {
    "en": "venezuela-special-taxpayers-seniat",
    "es": "venezuela-special-taxpayers-seniat"
  }
};
