/**
 * Map of insight slug -> { en, es } slugs for locale switching.
 * Generated by scripts/generate-insights-locale-map.js - do not edit by hand.
 */
export const insightsLocaleMap: Record<string, { en: string; es: string }> = {
  "arbitraje-comercial-resolucion-controversias-venezuela": {
    "en": "commercial-arbitration-resolving-disputes-venezuela",
    "es": "arbitraje-comercial-resolucion-controversias-venezuela"
  },
  "commercial-arbitration-resolving-disputes-venezuela": {
    "en": "commercial-arbitration-resolving-disputes-venezuela",
    "es": "arbitraje-comercial-resolucion-controversias-venezuela"
  },
  "aspectos-constituir-empresa-venezuela": {
    "en": "incorporating-company-venezuela",
    "es": "aspectos-constituir-empresa-venezuela"
  },
  "incorporating-company-venezuela": {
    "en": "incorporating-company-venezuela",
    "es": "aspectos-constituir-empresa-venezuela"
  },
  "bonos-divisas-caracter-salarial-venezuela": {
    "en": "foreign-currency-bonuses-salary-venezuela",
    "es": "bonos-divisas-caracter-salarial-venezuela"
  },
  "foreign-currency-bonuses-salary-venezuela": {
    "en": "foreign-currency-bonuses-salary-venezuela",
    "es": "bonos-divisas-caracter-salarial-venezuela"
  },
  "cedca-new-arbitration-rules-2026-venezuela": {
    "en": "cedca-new-arbitration-rules-2026-venezuela",
    "es": "cedca-nuevo-reglamento-conciliacion-arbitraje-2026"
  },
  "cedca-nuevo-reglamento-conciliacion-arbitraje-2026": {
    "en": "cedca-new-arbitration-rules-2026-venezuela",
    "es": "cedca-nuevo-reglamento-conciliacion-arbitraje-2026"
  },
  "corporate-good-standing-venezuela": {
    "en": "corporate-good-standing-venezuela",
    "es": "empresas-corporativamente-al-dia-es"
  },
  "empresas-corporativamente-al-dia-es": {
    "en": "corporate-good-standing-venezuela",
    "es": "empresas-corporativamente-al-dia-es"
  },
  "fintech-venezuela-itfb-regulation": {
    "en": "fintech-venezuela-itfb-regulation",
    "es": "fintech-venezuela-itfb-sudeban"
  },
  "fintech-venezuela-itfb-sudeban": {
    "en": "fintech-venezuela-itfb-regulation",
    "es": "fintech-venezuela-itfb-sudeban"
  },
  "ofac-general-licenses-venezuela-march-2026": {
    "en": "ofac-general-licenses-venezuela-march-2026",
    "es": "ofac-licencias-generales-venezuela-marzo-2026"
  },
  "ofac-licencias-generales-venezuela-marzo-2026": {
    "en": "ofac-general-licenses-venezuela-march-2026",
    "es": "ofac-licencias-generales-venezuela-marzo-2026"
  },
  "payment-service-providers-venezuela": {
    "en": "payment-service-providers-venezuela",
    "es": "proveedores-servicios-pago-venezuela"
  },
  "proveedores-servicios-pago-venezuela": {
    "en": "payment-service-providers-venezuela",
    "es": "proveedores-servicios-pago-venezuela"
  }
};
